### ISSUE TITLE
Model storing

### ISSUE THREAD

**Issue by Shemka** [kalekiu/easyesn#10]
Hello, how can I save already trained model?

**Comment by ikespand** [comment]
As this library is build upon Scikit-learn, so you can dump trained model data (i.e. after esn.fit) using joblib.
```
from sklearn.externals import joblib
model_save = "esn_model.sav"
joblib.dump(esn, model_save)
```
You can then load model as
```
loaded_model = joblib.load(filename)
Y_new_prediction = loaded_model.predict(X_new)
```
