### ISSUE TITLE
Disable multiprocess for Windows Anaconda?

### ISSUE THREAD

**Issue by jabowery** [kalekiu/easyesn#2]
I tried setting `nWorkers=1` in the call to `SpatioTemporalESN` but it still hangs upon line 71's call to `Manager()`.

This appears related to a problem with the Windows implementation of the `multiprocess` module.

Is there a simple way of bypassing the use of multiprocessing?

**Comment by FlashTek** [comment]
Can you please add the code you used? Or did you use one of the example notebooks? This might help to detect the real problem.

At the momen there is no way to bypass the multiprocessing other than setting the number of workers to `1`.  But i do not think that this is a Windows problem, as I mainly develop on a Windows 10 machine. Therefore, the code is tested to be working on a Anaconda Windows 10 setup and at least on one Unix version.

**Comment by FlashTek** [comment]
I made some vast improvements on the `SpatioTemporalESN` in the past commits in regards of the performance (on Linux as well as on Windows). So maybe your issue is now solved, too. If this is not the case, feel free to open this issue again.
