### ISSUE TITLE
ClassificationESN super

### ISSUE THREAD

**Issue by willwill99** [kalekiu/easyesn#3]
To get the example to run I had to change

weight_generation to weightGeneration
and inputDensity to input_density

Cheers.

**Comment by ShunLiu1992** [comment]
It still got the bug as follows when I ran ClassificationESN,  could you please let me know how to fix it? I do not understand willwill99's comment.

> TypeError: __init__() got an unexpected keyword argument 'weight_generation'

**Comment by FlashTek** [comment]
I am working on a fix and will update the repository and the `pip` package tomorrow/in the next days.

**Comment by FlashTek** [comment]
@willwill99 @ShunLiu1992 Please test your code again with the latest version here at Github or version 0.1.3.6 at `pip` and check if the issue is solved.

**Comment by FlashTek** [comment]
@willwill99 @ShunLiu1992 If there are no more comments from your side I will consider this issue as solved. Reopen it, if this is not the case.
