### ISSUE TITLE
Syntax error in BaseESN?

### ISSUE THREAD

**Issue by BorisWiegand** [kalekiu/easyesn#5]
When I try to execute the code for fitting a new ESN, my python interpreter complains about "invalid syntax" in BaseESN.py.

The constructor of BaseESN in https://github.com/kalekiu/easyesn/blob/master/src/easyesn/easyesn/BaseESN.py indeed shows a default value of 0.2 for a non-specified argument. With other words: the argument name seems to be missing.

**Comment by FlashTek** [comment]
Thanks! That has been a bad typo. I fixed it and uploaded the new version on GitHub and on pip as well.
