### ISSUE TITLE
multivariate time-series classification problem

### ISSUE THREAD

**Issue by rjpg** [kalekiu/easyesn#7]
hello,

I would like to use this implementation for a multivariable time series classification.

My dataset is composed of several examples of 9 time-series segments with 128 steps.
Each segment belongs to one of 5 classes.

Input shape (2128,128,9) -> (number of examples, time-steps, variables)
output shape (2128,1) - > (number of examples, class)
(the class is one-hot-encoded so I use categorical-cross-entropy with 5 neurons output layer)

I have it working with a LSTMs based model.

I would like to test with easyesn to see if there is any improvement.

If you can help to provide some lights/base code to do this adaptation it would be nice.

Thanks in advance,
Rui

**Comment by gozsoy14** [comment]
@rjpg were you able to reach a solution? coz i got the same problem here.
maybe a solution is passing only one sample at a time?

**Comment by zimmerrol** [comment]
To classify time series you can use the `ClassificationESN` class in `easyesn`. Its fit function expects input data of the shape `(n_samples, n_time_steps, dimensions)` and output data of the shape `(n_samples)`, which corresponds to the class labels.
